version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: quarkus
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bereal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  quarkus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quarkus-app
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/bereal_db
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

volumes:
  postgres_data:
