version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: my-quarkus
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bereal_db
    networks:
      - q-net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-app
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://quarkus:5432/bereal_db
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
  #  depends_on:
  #    - keycloak

 # keycloak:
 #   image: quay.io/keycloak/keycloak:latest
 #   build:
 #     dockerfile: src/main/docker/Dockerfile
 #   container_name: keycloak2
 #   environment:
 #     KC_DB: postgres
 #     KC_DB_URL: jdbc:postgresql://postgresql:5432/bereal_db
 #     KC_DB_USERNAME: user
 #     KC_DB_PASSWORD: password
 #     KC_DB_URL_PORT: 8081
 #   networks:
 #     - q-net
 #   ports:
 #     - "8082:8082"
 #   depends_on:
 #     - postgresql
 #   command: ["start-dev"]

volumes:
  postgres_data:

networks:
  q-net:
    driver: bridge
