apiVersion: v1
kind: Service
metadata:
  name: k8s-test-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "2"
    service.beta.kubernetes.io/do-loadbalancer-deny-rules: "cidr:198.51.100.0/16"
spec:
  type: LoadBalancer
  selector:
    app: k8s-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
