# postgres-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: bereal_db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  init.sql: |
    -- Your SQL initialization script here
    -- Create Users Table
    CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    phone_number VARCHAR(15) NOT NULL,
    birth_date DATE NOT NULL,
    nickname VARCHAR(255),
    UNIQUE(phone_number, birth_date)
    );
    
    -- Create BeReals Table
    CREATE TABLE bereals (
    bereal_id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    front_photo BYTEA NOT NULL,
    back_photo BYTEA NOT NULL,
    location VARCHAR(255),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, date_created)
    );
    
    -- Create Friendships Table
    CREATE TABLE friendships (
    user_id INT REFERENCES users(user_id),
    friend_id INT REFERENCES users(user_id),
    PRIMARY KEY(user_id, friend_id),
    CHECK (user_id <> friend_id)
    );
